host: 0.0.0.0

# GitHub Pages URL (NO custom domain)
url: https://taricohenry.github.io
baseurl: /ashley-and-navin

exclude:
  - firebase
  - firebase/**
  - vendor
  - vendor/**
  - node_modules
  - node_modules/**
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
